### PR TITLE
feat: Add support for AXFrame(CGRect) value type

### PR DESCRIPTION
**Pull request by timurco**
Added support for AXFrame value type. With x,y, width and height attributes.
..
P.S. This is my first pull request. Sorry if something is not correct

### CODE REVIEW

**Comment by daveenguyen** [comment]
Thanks for the contribution!

I haven't touched this in a while and it looks like the build is broken.
I'll look into it tomorrow and hopefully get your changes merged in.



In the meantime, can you do me a favor and find/share a native macO example of AXFrame?

And if possible add a test like this
https://github.com/daveenguyen/atomacos/blob/d1836345e29d54950e61d40bd24490a715280f77/tests/test_atomacos.py#L87-L91


`front_title_ui` is from conftest.py if that part is confusing
https://github.com/daveenguyen/atomacos/blob/d1836345e29d54950e61d40bd24490a715280f77/tests/conftest.py#L55-L72

Thanks again for your help

**Comment by timurco** [comment]
It's just like a CGPosition and CGSize, but combined in one CGRect. Native Finder have this by default
Here is screenshot of finder

But I use this to automate Screenflow with auto-editing.

A little bit later I will add that tests. And need to create new pull requests with 2 commits (AXFrame+Tests), Right?

**Comment by daveenguyen** [comment]
You can continue working on your branch and it'll update this pull request. No need to create a new pull request.
Just got travis working again in the latest master.

**Review by daveenguyen — CHANGES_REQUESTED** [review]
Changes looking good.
Please add test if you can.
Would also need to pull in latest master so travis would work.

**Pull request merged**
